# Generated by Django 4.2.11 on 2024-03-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('message', models.TextField(verbose_name='message')),
                ('region', models.CharField(choices=[('Middle East and North Africa', 'Middle East and North Africa'), ('USA', 'USA'), ('Europe', 'Europe'), ('Asia', 'Asia'), ('Australia', 'Australia'), ('Africa', 'Africa'), ('South America', 'South America'), ('Central America', 'Central America'), ('Caribbean', 'Caribbean'), ('Other', 'Other')], default='Middle East and North Africa', max_length=100)),
                ('industry', models.CharField(choices=[('Agriculture', 'Agriculture'), ('Automotive', 'Automotive'), ('Banking', 'Banking'), ('Construction', 'Construction'), ('Education', 'Education'), ('Energy', 'Energy'), ('Entertainment', 'Entertainment'), ('Fashion', 'Fashion'), ('Finance', 'Finance'), ('Food and Beverage', 'Food and Beverage'), ('Healthcare', 'Healthcare'), ('Hospitality', 'Hospitality'), ('Insurance', 'Insurance'), ('Manufacturing', 'Manufacturing'), ('Media', 'Media'), ('Pharmaceutical', 'Pharmaceutical'), ('Real Estate', 'Real Estate'), ('Retail', 'Retail'), ('Technology', 'Technology'), ('Telecommunications', 'Telecommunications'), ('Transportation', 'Transportation'), ('Travel', 'Travel'), ('Utilities', 'Utilities'), ('Other', 'Other')], default='Agriculture', max_length=100, verbose_name='industry')),
            ],
        ),
    ]
