# Generated by Django 4.2.11 on 2024-03-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('region', models.CharField(blank=True, choices=[('Middle East and North Africa', 'Middle East and North Africa'), ('USA', 'USA'), ('Europe', 'Europe'), ('Asia', 'Asia'), ('Australia', 'Australia'), ('Africa', 'Africa'), ('South America', 'South America'), ('Central America', 'Central America'), ('Caribbean', 'Caribbean'), ('Other', 'Other')], default='Middle East and North Africa', max_length=100, verbose_name='region')),
                ('date', models.DateField(verbose_name='date')),
                ('time', models.TimeField(verbose_name='time')),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
            ],
        ),
    ]
