# Generated by Django 4.2.11 on 2024-03-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_meetingrequest_newslettersubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsubmission',
            name='region',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='meetingrequest',
            name='region',
            field=models.CharField(blank=True, max_length=100, verbose_name='region'),
        ),
    ]
