# Generated by Django 4.2.11 on 2024-03-23 16:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_contactsubmission_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactsubmission',
            name='region',
        ),
        migrations.RemoveField(
            model_name='meetingrequest',
            name='date',
        ),
        migrations.RemoveField(
            model_name='meetingrequest',
            name='region',
        ),
        migrations.RemoveField(
            model_name='meetingrequest',
            name='time',
        ),
        migrations.AddField(
            model_name='meetingrequest',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='datetime'),
            preserve_default=False,
        ),
    ]
